### ISSUE TITLE
40px Worth of `padding-left` Appears on Nav

### ISSUE THREAD

**Issue by gelafin** [gelafin/flexbox-holy-grail#1]
This line is affected, even though it is not selected anywhere in the CSS other than these:
```CSS
nav ul{
    list-style-type: none;
}
.flexbox-container {
    display:flex;
    flex-flow: row wrap;
}
```
https://github.com/gelafin/flexbox-holy-grail/blob/aa6e98aa90edee69e611abe55bb40527ccc168a1/index.html#L11
